In [1]:
print("Dataset audit notebook is working!")

Dataset audit notebook is working!

In [3]:
import pandas as pd
from pathlib import Path

# Project root directory
PROJECT_ROOT = Path.cwd().parent

# Dataset paths
DATA_DIR = PROJECT_ROOT / "data" / "raw"

file_2024 = DATA_DIR / "players_data-2024_2025.csv"
file_2025 = DATA_DIR / "players_data-2025_2026 (1).csv"

# Load datasets
df_2024 = pd.read_csv(file_2024)
df_2025 = pd.read_csv(file_2025)

print("2024/25 dataset loaded successfully.")
print("2025/26 dataset loaded successfully.")

2024/25 dataset loaded successfully.
2025/26 dataset loaded successfully.

In [5]:
print("2024/25 shape:", df_2024.shape)
print("2025/26 shape:", df_2025.shape)

2024/25 shape: (2854, 267)
2025/26 shape: (2839, 102)

In [6]:
columns_2024 = set(df_2024.columns)
columns_2025 = set(df_2025.columns)

print("Columns only in 2024/25:")
print(sorted(columns_2024 - columns_2025))

print("\nColumns only in 2025/26:")
print(sorted(columns_2025 - columns_2024))

print("\nNumber of columns in 2024/25:", len(columns_2024))
print("Number of columns in 2025/26:", len(columns_2025))
print("Same columns:", columns_2024 == columns_2025)

Columns only in 2024/25:
['#OPA', '#OPA/90', '/90', '1/3', '1/3_stats_possession', '90s_stats_defense', '90s_stats_gca', '90s_stats_keeper_adv', '90s_stats_passing', '90s_stats_passing_types', '90s_stats_possession', 'A-xAG', 'Age_stats_defense', 'Age_stats_gca', 'Age_stats_keeper_adv', 'Age_stats_passing', 'Age_stats_passing_types', 'Age_stats_possession', 'Ast_stats_passing', 'Att', 'Att (GK)', 'Att 3rd', 'Att 3rd_stats_possession', 'Att Pen', 'Att_stats_defense', 'Att_stats_keeper_adv', 'Att_stats_passing_types', 'Att_stats_possession', 'AvgDist', 'AvgLen', 'Blocks', 'Blocks_stats_defense', 'Born_stats_defense', 'Born_stats_gca', 'Born_stats_keeper_adv', 'Born_stats_passing', 'Born_stats_passing_types', 'Born_stats_possession', 'CK', 'CK_stats_keeper_adv', 'CPA', 'Carries', 'Clr', 'Cmp', 'Cmp%', 'Cmp%_stats_keeper_adv', 'Cmp_stats_keeper_adv', 'Cmp_stats_passing_types', 'Comp_stats_defense', 'Comp_stats_gca', 'Comp_stats_keeper_adv', 'Comp_stats_passing', 'Comp_stats_passing_types', 'Comp_stats_possession', 'CrsPA', 'Crs_stats_misc', 'Dead', 'Def', 'Def 3rd', 'Def 3rd_stats_possession', 'Def Pen', 'Dis', 'Dist', 'Err', 'FK', 'FK_stats_keeper_adv', 'FK_stats_passing_types', 'Fld_stats_misc', 'G-xG', 'GA_stats_keeper_adv', 'GCA', 'GCA90', 'In', 'Int_stats_misc', 'KP', 'Launch%', 'Live', 'Live_stats_possession', 'Lost', 'Lost_stats_misc', 'Mid 3rd', 'Mid 3rd_stats_possession', 'Mis', 'Nation_stats_defense', 'Nation_stats_gca', 'Nation_stats_keeper_adv', 'Nation_stats_passing', 'Nation_stats_passing_types', 'Nation_stats_possession', 'OG_stats_keeper_adv', 'Off_stats_misc', 'Opp', 'Out', 'PKA_stats_keeper_adv', 'PKcon', 'PKwon', 'PPA', 'PSxG', 'PSxG+/-', 'PSxG/SoT', 'Pass', 'PassDead', 'PassLive', 'Pos_stats_defense', 'Pos_stats_gca', 'Pos_stats_keeper_adv', 'Pos_stats_passing', 'Pos_stats_passing_types', 'Pos_stats_possession', 'PrgC', 'PrgC_stats_possession', 'PrgDist', 'PrgDist_stats_possession', 'PrgP', 'PrgP_stats_passing', 'PrgR', 'PrgR_stats_possession', 'Rec', 'Recov', 'Rk_stats_defense', 'Rk_stats_gca', 'Rk_stats_keeper_adv', 'Rk_stats_passing', 'Rk_stats_passing_types', 'Rk_stats_possession', 'SCA', 'SCA90', 'Sh_stats_defense', 'Sh_stats_gca', 'Stp', 'Stp%', 'Str', 'Succ', 'Succ%', 'Sw', 'TB', 'TI', 'TO', 'Thr', 'Tkl', 'Tkl%', 'Tkl+Int', 'TklW_stats_misc', 'Tkld', 'Tkld%', 'TotDist', 'TotDist_stats_possession', 'Touches', 'Won', 'Won%', 'np:G-xG', 'npxG', 'npxG+xAG', 'npxG/Sh', 'npxG_stats_shooting', 'onxG', 'onxGA', 'xA', 'xAG', 'xAG_stats_passing', 'xG', 'xG+/-', 'xG+/-90', 'xG+xAG', 'xG_stats_shooting']

Columns only in 2025/26:
[]

Number of columns in 2024/25: 267
Number of columns in 2025/26: 102
Same columns: False

In [7]:
common_columns = sorted(columns_2024 & columns_2025)

print("Number of common columns:", len(common_columns))
print("\nCommon columns:")
for column in common_columns:
    print(column)

Number of common columns: 102

Common columns:
+/-
+/-90
2CrdY
90s
90s_stats_keeper
90s_stats_misc
90s_stats_playing_time
90s_stats_shooting
Age
Age_stats_keeper
Age_stats_misc
Age_stats_playing_time
Age_stats_shooting
Ast
Born
Born_stats_keeper
Born_stats_misc
Born_stats_playing_time
Born_stats_shooting
CS
CS%
Comp
Comp_stats_keeper
Comp_stats_misc
Comp_stats_playing_time
Comp_stats_shooting
Compl
CrdR
CrdR_stats_misc
CrdY
CrdY_stats_misc
Crs
D
Fld
Fls
G+A
G+A-PK
G-PK
G/Sh
G/SoT
GA
GA90
Gls
Gls_stats_shooting
Int
L
MP
MP_stats_keeper
MP_stats_playing_time
Min
Min%
Min_stats_keeper
Min_stats_playing_time
Mn/MP
Mn/Start
Mn/Sub
Nation
Nation_stats_keeper
Nation_stats_misc
Nation_stats_playing_time
Nation_stats_shooting
OG
Off
On-Off
PK
PKA
PK_stats_shooting
PKatt
PKatt_stats_keeper
PKatt_stats_shooting
PKm
PKsv
PPM
Player
Pos
Pos_stats_keeper
Pos_stats_misc
Pos_stats_playing_time
Pos_stats_shooting
Rk
Rk_stats_keeper
Rk_stats_misc
Rk_stats_playing_time
Rk_stats_shooting
Save%
Saves
Sh
Sh/90
SoT
SoT%
SoT/90
SoTA
Squad
Starts
Starts_stats_keeper
Starts_stats_playing_time
Subs
TklW
W
onG
onGA
unSub

In [8]:
pd.set_option("display.max_rows", 150)

column_info = pd.DataFrame({
    "column": df_2025.columns,
    "dtype": df_2025.dtypes.astype(str),
    "missing": df_2025.isna().sum(),
    "unique_values": df_2025.nunique()
})

column_info

,column,dtype,missing,unique_values
Rk,Rk,int64,0,2839
Player,Player,str,0,2687
Nation,Nation,str,3,115
Pos,Pos,str,0,9
Squad,Squad,str,0,96
Comp,Comp,str,0,5
Age,Age,float64,2,27
Born,Born,float64,2,28
MP,MP,int64,0,38
Starts,Starts,int64,0,39
Min,Min,int64,0,1684
90s,90s,float64,0,370
Gls,Gls,int64,0,25
Ast,Ast,int64,0,18
G+A,G+A,int64,0,32
G-PK,G-PK,int64,0,22
PK,PK,int64,0,10
PKatt,PKatt,int64,0,11
CrdY,CrdY,int64,0,14
CrdR,CrdR,int64,0,4
G+A-PK,G+A-PK,float64,0,124
Rk_stats_keeper,Rk_stats_keeper,float64,2645,194
Nation_stats_keeper,Nation_stats_keeper,str,2645,46
Pos_stats_keeper,Pos_stats_keeper,str,2645,1
Comp_stats_keeper,Comp_stats_keeper,str,2645,5
Age_stats_keeper,Age_stats_keeper,float64,2645,22
Born_stats_keeper,Born_stats_keeper,float64,2645,23
MP_stats_keeper,MP_stats_keeper,float64,2645,38
Starts_stats_keeper,Starts_stats_keeper,float64,2645,38
Min_stats_keeper,Min_stats_keeper,float64,2645,96
90s_stats_keeper,90s_stats_keeper,float64,2645,82
GA,GA,float64,2645,60
GA90,GA90,float64,2645,100
SoTA,SoTA,float64,2645,114
Saves,Saves,float64,2645,93
Save%,Save%,float64,2649,116
W,W,float64,2645,27
D,D,float64,2645,16
L,L,float64,2645,23
CS,CS,float64,2645,18
CS%,CS%,float64,2651,87
PKatt_stats_keeper,PKatt_stats_keeper,float64,2645,12
PKA,PKA,float64,2645,10
PKsv,PKsv,float64,2645,4
PKm,PKm,float64,2645,4
Rk_stats_shooting,Rk_stats_shooting,int64,0,2839
Nation_stats_shooting,Nation_stats_shooting,str,3,115
Pos_stats_shooting,Pos_stats_shooting,str,0,9
Comp_stats_shooting,Comp_stats_shooting,str,0,5
Age_stats_shooting,Age_stats_shooting,float64,2,27
Born_stats_shooting,Born_stats_shooting,float64,2,28
90s_stats_shooting,90s_stats_shooting,float64,0,370
Gls_stats_shooting,Gls_stats_shooting,int64,0,25
Sh,Sh,int64,0,106
SoT,SoT,int64,0,49
SoT%,SoT%,float64,490,305
Sh/90,Sh/90,float64,0,425
SoT/90,SoT/90,float64,0,214
G/Sh,G/Sh,float64,490,36
G/SoT,G/SoT,float64,826,62
PK_stats_shooting,PK_stats_shooting,int64,0,10
PKatt_stats_shooting,PKatt_stats_shooting,int64,0,11
Rk_stats_playing_time,Rk_stats_playing_time,int64,0,2839
Nation_stats_playing_time,Nation_stats_playing_time,str,3,115
Pos_stats_playing_time,Pos_stats_playing_time,str,0,9
Comp_stats_playing_time,Comp_stats_playing_time,str,0,5
Age_stats_playing_time,Age_stats_playing_time,float64,2,27
Born_stats_playing_time,Born_stats_playing_time,float64,2,28
MP_stats_playing_time,MP_stats_playing_time,int64,0,38
Min_stats_playing_time,Min_stats_playing_time,int64,0,1684
Mn/MP,Mn/MP,int64,0,90
Min%,Min%,float64,0,858
90s_stats_playing_time,90s_stats_playing_time,float64,0,370
Starts_stats_playing_time,Starts_stats_playing_time,int64,0,39
Mn/Start,Mn/Start,float64,362,56
Compl,Compl,int64,0,39
Subs,Subs,int64,0,28
Mn/Sub,Mn/Sub,float64,377,64
unSub,unSub,int64,0,38
PPM,PPM,float64,0,242
onG,onG,int64,0,83
onGA,onGA,int64,0,71
+/-,+/-,int64,0,94
+/-90,+/-90,float64,0,514
On-Off,On-Off,float64,25,561
Rk_stats_misc,Rk_stats_misc,int64,0,2839
Nation_stats_misc,Nation_stats_misc,str,3,115
Pos_stats_misc,Pos_stats_misc,str,0,9
Comp_stats_misc,Comp_stats_misc,str,0,5
Age_stats_misc,Age_stats_misc,float64,2,27
Born_stats_misc,Born_stats_misc,float64,2,28
90s_stats_misc,90s_stats_misc,float64,0,370
CrdY_stats_misc,CrdY_stats_misc,int64,0,14
CrdR_stats_misc,CrdR_stats_misc,int64,0,4
2CrdY,2CrdY,int64,0,3
Fls,Fls,int64,0,69
Fld,Fld,int64,0,80
Off,Off,int64,0,31
Crs,Crs,int64,0,174
Int,Int,int64,0,60
TklW,TklW,int64,0,67
OG,OG,int64,0,3

In [9]:
print("2025/26 positions:")
print(df_2025["Pos"].value_counts())

print("\n2024/25 positions:")
print(df_2024["Pos"].value_counts())

2025/26 positions:
Pos
MF       922
DF       705
FW       398
MF,FW    217
GK       194
FW,MF    144
DF,MF    141
MF,DF    115
DF,FW      3
Name: count, dtype: int64

2024/25 positions:
Pos
DF       859
MF       589
FW       371
FW,MF    325
MF,FW    230
GK       212
DF,MF    110
MF,DF     81
DF,FW     53
FW,DF     24
Name: count, dtype: int64

In [10]:
print("2025/26 leagues:")
print(df_2025["Comp"].value_counts())

print("\n2024/25 leagues:")
print(df_2024["Comp"].value_counts())

2025/26 leagues:
Comp
es La Liga            611
it Serie A            609
fr Ligue 1            561
eng Premier League    551
de Bundesliga         507
Name: count, dtype: int64

2024/25 leagues:
Comp
it Serie A            634
es La Liga            601
eng Premier League    574
fr Ligue 1            553
de Bundesliga         492
Name: count, dtype: int64

In [11]:
player_counts = df_2025["Player"].value_counts()

repeated_players = player_counts[player_counts > 1]

print("Number of players appearing more than once:",
      len(repeated_players))

print("\nRepeated players:")
print(repeated_players.head(20))

Number of players appearing more than once: 151

Repeated players:
Player
Nicolás González      3
Himad Abdelli         2
Simon Adingra         2
Nayef Aguerd          2
Ilias Akhomach        2
Alfon                 2
Aaron Anselmino       2
Leon Bailey           2
Darryl Bakola         2
Dilane Bakwa          2
Tommaso Baldanzi      2
Sheraldo Becker       2
Jeanuël Belocian      2
Fran Beltrán          2
Eliesse Ben Seghir    2
Oscar Bobb            2
Jeremie Boga          2
Badredine Bouanani    2
Marco Brescianini     2
Facundo Buonanotte    2
Name: count, dtype: int64

In [12]:
example_player = repeated_players.index[0]

df_2025[df_2025["Player"] == example_player][
    ["Player", "Pos", "Squad", "Comp", "Age", "Min"]
]

                Player    Pos            Squad                Comp   Age   Min
1026  Nicolás González     MF  Manchester City  eng Premier League  23.0  1569
1027  Nicolás González  MF,DF  Atlético Madrid          es La Liga  27.0  1448
1028  Nicolás González  FW,MF         Juventus          it Serie A  27.0    19

In [13]:
important_columns = [
    "Player",
    "Nation",
    "Pos",
    "Squad",
    "Comp",
    "Age",
    "MP",
    "Starts",
    "Min",
    "90s",
    "Gls",
    "Ast",
    "G+A",
    "G-PK",
    "xG",
    "xAG",
    "npxG",
    "Sh",
    "SoT",
    "Sh/90",
    "SoT/90",
    "G/Sh",
    "G/SoT",
    "TklW",
    "Int",
    "GA",
    "Saves",
    "Save%",
    "CS",
    "Touches",
    "Carries",
    "PrgC",
    "PrgP",
    "PrgR",
    "KP",
    "xA",
    "PPA",
]

available_columns = [
    col for col in important_columns
    if col in df_2025.columns
]

missing_columns = [
    col for col in important_columns
    if col not in df_2025.columns
]

print("AVAILABLE:")
print(available_columns)

print("\nNOT AVAILABLE:")
print(missing_columns)

AVAILABLE:
['Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'Sh', 'SoT', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'TklW', 'Int', 'GA', 'Saves', 'Save%', 'CS']

NOT AVAILABLE:
['xG', 'xAG', 'npxG', 'Touches', 'Carries', 'PrgC', 'PrgP', 'PrgR', 'KP', 'xA', 'PPA']

In [15]:
important_features_2024 = [
    "Player",
    "Nation",
    "Pos",
    "Squad",
    "Comp",
    "Age",
    "MP",
    "Starts",
    "Min",
    "90s",
    "Gls",
    "Ast",
    "G+A",
    "G-PK",
    "xG",
    "xAG",
    "npxG",
    "Sh",
    "SoT",
    "Sh/90",
    "SoT/90",
    "Tkl",
    "TklW",
    "Int",
    "Blocks",
    "Clr",
    "Touches",
    "Carries",
    "PrgC",
    "PrgP",
    "PrgR",
    "KP",
    "xA",
    "PPA",
    "Recov",
]

available_2024 = [
    col for col in important_features_2024
    if col in df_2024.columns
]

missing_2024 = [
    col for col in important_features_2024
    if col not in df_2024.columns
]

print("AVAILABLE IN 2024/25:")
print(available_2024)

print("\nNOT AVAILABLE IN 2024/25:")
print(missing_2024)

AVAILABLE IN 2024/25:
['Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'xG', 'xAG', 'npxG', 'Sh', 'SoT', 'Sh/90', 'SoT/90', 'Tkl', 'TklW', 'Int', 'Blocks', 'Clr', 'Touches', 'Carries', 'PrgC', 'PrgP', 'PrgR', 'KP', 'xA', 'PPA', 'Recov']

NOT AVAILABLE IN 2024/25:
[]

In [16]:
core_features = [
    "Player", "Nation", "Pos", "Squad", "Comp", "Age",
    "MP", "Starts", "Min", "90s",
    "Gls", "Ast", "xG", "xAG", "npxG",
    "Sh", "SoT", "Sh/90", "SoT/90",
    "Tkl", "TklW", "Int", "Blocks", "Clr",
    "Touches", "Carries", "PrgC", "PrgP", "PrgR",
    "KP", "xA", "PPA", "Recov"
]

audit_2024 = pd.DataFrame({
    "column": core_features,
    "dtype": [df_2024[col].dtype for col in core_features],
    "missing_count": [df_2024[col].isna().sum() for col in core_features],
    "missing_percent": [
        round(df_2024[col].isna().mean() * 100, 2)
        for col in core_features
    ]
})

audit_2024

     column    dtype  missing_count  missing_percent
0    Player      str              0             0.00
1    Nation      str              7             0.25
2       Pos      str              0             0.00
3     Squad      str              0             0.00
4      Comp      str              0             0.00
5       Age  float64              8             0.28
6        MP    int64              0             0.00
7    Starts    int64              0             0.00
8       Min    int64              0             0.00
9       90s  float64              0             0.00
10      Gls    int64              0             0.00
11      Ast    int64              0             0.00
12       xG  float64              0             0.00
13      xAG  float64              0             0.00
14     npxG  float64              0             0.00
15       Sh    int64              0             0.00
16      SoT    int64              0             0.00
17    Sh/90  float64              0             0.00
18   SoT/90  float64              0             0.00
19      Tkl    int64              0             0.00
20     TklW    int64              0             0.00
21      Int    int64              0             0.00
22   Blocks    int64              0             0.00
23      Clr    int64              0             0.00
24  Touches    int64              0             0.00
25  Carries    int64              0             0.00
26     PrgC    int64              0             0.00
27     PrgP    int64              0             0.00
28     PrgR    int64              0             0.00
29       KP    int64              0             0.00
30       xA  float64              0             0.00
31      PPA    int64              0             0.00
32    Recov    int64              0             0.00

In [17]:
print(audit_2024.to_string(index=False))

 column   dtype  missing_count  missing_percent
 Player     str              0             0.00
 Nation     str              7             0.25
    Pos     str              0             0.00
  Squad     str              0             0.00
   Comp     str              0             0.00
    Age float64              8             0.28
     MP   int64              0             0.00
 Starts   int64              0             0.00
    Min   int64              0             0.00
    90s float64              0             0.00
    Gls   int64              0             0.00
    Ast   int64              0             0.00
     xG float64              0             0.00
    xAG float64              0             0.00
   npxG float64              0             0.00
     Sh   int64              0             0.00
    SoT   int64              0             0.00
  Sh/90 float64              0             0.00
 SoT/90 float64              0             0.00
    Tkl   int64              0             0.00
   TklW   int64              0             0.00
    Int   int64              0             0.00
 Blocks   int64              0             0.00
    Clr   int64              0             0.00
Touches   int64              0             0.00
Carries   int64              0             0.00
   PrgC   int64              0             0.00
   PrgP   int64              0             0.00
   PrgR   int64              0             0.00
     KP   int64              0             0.00
     xA float64              0             0.00
    PPA   int64              0             0.00
  Recov   int64              0             0.00

In [18]:
repeated_2024 = df_2024["Player"].value_counts()

repeated_2024 = repeated_2024[repeated_2024 > 1]

print("Players appearing more than once in 2024/25:",
      len(repeated_2024))

print("\nTop repeated players:")
print(repeated_2024.head(20))

Players appearing more than once in 2024/25: 152

Top repeated players:
Player
Max Aarons           2
Tammy Abraham        2
Akor Adams           2
Emmanuel Agbadou     2
Joseph Aidoo         2
Carlos Alcaraz       2
Carles Aleñá         2
Samuel Amo-Ameyaw    2
Mathis Amougou       2
Joachim Andersen     2
Antony               2
Marco Asensio        2
Jordan Ayew          2
Adam Aznou           2
Juma Bah             2
Mitchel Bakker       2
Ridle Baku           2
Valentín Barco       2
Reda Belahyane       2
Raoul Bellanova      2
Name: count, dtype: int64

In [19]:
example_player_2024 = repeated_2024.index[0]

df_2024[df_2024["Player"] == example_player_2024][
    ["Player", "Pos", "Squad", "Comp", "Age", "Min"]
]

       Player    Pos        Squad                Comp   Age  Min
0  Max Aarons     DF  Bournemouth  eng Premier League  24.0   86
1  Max Aarons  DF,MF     Valencia          es La Liga  24.0  120

In [20]:
player = repeated_2024.index[0]

columns_to_check = [
    "Player",
    "Pos",
    "Squad",
    "Comp",
    "Age",
    "Min",
    "90s",
    "Gls",
    "Ast",
    "xG",
    "xAG",
    "npxG",
    "PrgP",
    "PrgC",
    "PrgR",
    "KP",
    "xA",
    "PPA",
    "Tkl",
    "TklW",
    "Int",
    "Blocks",
    "Touches",
    "Carries"
]

df_2024[df_2024["Player"] == player][columns_to_check]

,Player,Pos,Squad,Comp,Age,Min,90s,Gls,Ast,xG,...,PrgR,KP,xA,PPA,Tkl,TklW,Int,Blocks,Touches,Carries
0,Max Aarons,DF,Bournemouth,eng Premier League,24.0,86,1.0,0,0,0.0,...,3,0,0.0,0,2,2,1,1,73,41
1,Max Aarons,"DF,MF",Valencia,es La Liga,24.0,120,1.3,0,0,0.0,...,10,1,0.0,0,4,4,0,1,85,46